### ISSUE TITLE
spider deals damage through corner

### ISSUE THREAD

**Issue by Thyrexx** [Three-s-A-Crowd-Games/Gerda#105]
related to #78 
Now the problem is that the hitbox of a spider goes through the corner and can deal damage.

**Comment by Jakllp** [comment]
That's easy enough to fix, we basically already do it:  
Right now the hitbox of the Spider is only actually there when the Spider is attacking OR in the time between it spawning and it attacking.  
The size of the hitbox is already stored `@onready`.

For the sake of usability of the 2D-Editor we should just set the size of it to 0 right after storing it.


OR you add a line of sight check to the damage-processing which is... imo ugly when there already kinda is a solution
