### ISSUE TITLE
enemy spawn issues

### ISSUE THREAD

**Issue by Thyrexx** [Three-s-A-Crowd-Games/Gerda#117]
- [x] spawn to close to each other
  -especially worms which can not move might spawn inside each other because the check whether there is something is only at a point and not an area.

- [x] spawn in wall
  - probably the same reason as above

**Comment by Jakllp** [comment]
![image](https://github.com/Three-s-A-Crowd-Games/Gerda/assets/57708725/3972f664-b2a0-40fe-9c17-dde600676a43)
