### ISSUE TITLE
better crafting/ore experience

### ISSUE THREAD

**Issue by Thyrexx** [Three-s-A-Crowd-Games/Gerda#119]
### Jira-Issue: [GER-56]  
---  
currently you spend to much time at the amboss for crafting.  
Ideas:
- more ammo per craft
- if possible craft stacks of 10
- ...

[GER-56]: https://thyrexx.atlassian.net/browse/GER-56?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Jakllp** [comment]
Ore:
- 1-2 per mined ore  

Crafting:
- 5er Stacks um es nicht zu schnell zu machen

And then test

**Comment by Jakllp** [comment]
Done in ca3055e
