### ISSUE TITLE
better damage feedback

### ISSUE THREAD

**Issue by Thyrexx** [Three-s-A-Crowd-Games/Gerda#126]
We need better an more feedback for the player when he receives damage.
- red flash at the screen border
- screenshake
- ...

also better poisoned feedback:
- more green tint
- green flash at screen border
- ...

**Comment by Jakllp** [comment]
Decided on:  
- Red "flash" around the screen for damage
- Potentially Screen-Shake (testing)
- Try Green around the screen whilst poisoned

**Comment by Jakllp** [comment]
Might need some adjustments but the functionality is there
