### ISSUE TITLE
No ore from chests

### ISSUE THREAD

**Issue by Thyrexx** [Three-s-A-Crowd-Games/Gerda#129]
### Jira-Issue: [GER-56]  
---  
remove the chance to get ore from chests because it is very underwhelming.

[GER-56]: https://thyrexx.atlassian.net/browse/GER-56?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by leolady02** [comment]
also: no ore from boss

**Comment by Thyrexx** [comment]
ore shouldn't get dropped anywhere now
