### ISSUE TITLE
nerf dash

### ISSUE THREAD

**Issue by Thyrexx** [Three-s-A-Crowd-Games/Gerda#132]
### Jira-Issue: [GER-56]  
--- 
Currently the dash is pretty powerful right from the start and there is not really a reason to get upgrades for it. So we should nerf it.

- only one dash at the beginning
- more dash cooldown

[GER-56]: https://thyrexx.atlassian.net/browse/GER-56?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Jakllp** [comment]
Needs to be reevaluated after the first part of #154 was done in e93cd21

**Comment by leolady02** [comment]
- only one dash at the beginning!
   - extra dashes are not special
