### ISSUE TITLE
How to play page 

### ISSUE THREAD

**Issue by Jakllp** [Three-s-A-Crowd-Games/Gerda#135]
### Jira-Issue: [GER-64]  
---  

[GER-64]: https://thyrexx.atlassian.net/browse/GER-64?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by leolady02** [comment]
- [ ] explain mutators 
  - how do they work?
  - 3 Intensities
  - choose after every biome
  - cannot be cahnged
- [ ] explain goal
  - How to find trapdoor-room
- [ ] explain Ore
  - what do I need it for?
  - how to craft -> Anvil
- [ ] explain Upgrades
  - What are they for?
  - How to distiguish them
  - Info in Pause Menu

**Comment by leolady02** [comment]
The Button in the Start Menu is not yet connected.
And changes to the texts are very welcome.
