### ISSUE TITLE
Performance-Improvements

### ISSUE THREAD

**Issue by Jakllp** [Three-s-A-Crowd-Games/Gerda#151]
### Jira-Issue: [GER-63]  
---  
- [x] Only have enemies in a certain range actually process
- [ ] Why are worms this performance hungry?

[GER-63]: https://thyrexx.atlassian.net/browse/GER-63?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by Thyrexx** [comment]
This issue will be closed due to the fact that the issues with the worm are a general issue with the extra viewports for entities and we don't have the time left to focus on this. The issue will be continued in #155
