### ISSUE TITLE
Worm sometimes shooting twice

### ISSUE THREAD

**Issue by Jakllp** [Three-s-A-Crowd-Games/Gerda#160]
Don't know how to perfectly reproduce it yet but here are two theories:

### 1
- Go into the range of the worm for an extended period of time until it wants to shoot.
- Exit the range
- Enter the range again letting it shoot this time
### 2
- Enter the range of one worm
- Kill it right before it wants to shoot
- Enter the range of another worm

### What does that mean?
Depending on what the cause is the way to fix it is vastly different.  

GLHF

**Comment by leolady02** [comment]
Theorie one works. That way you can even trigger the worm to shoot more than 2 projectiles.
Let the attack-animation start but interrupt it by exiting the worms range.
