### ISSUE TITLE
Wrong ordering with worm and chest

### ISSUE THREAD

**Issue by Thyrexx** [Three-s-A-Crowd-Games/Gerda#162]
![image](https://github.com/Three-s-A-Crowd-Games/Gerda/assets/96577754/dc87f7cd-6e5a-4f80-ad26-a42da1e0b0e3)

There is something wrong

**Comment by Jakllp** [comment]
![image](https://github.com/Three-s-A-Crowd-Games/Gerda/assets/57708725/c8301785-bcac-4159-870f-94cabb3c0b41)
?

**Comment by Jakllp** [comment]
MAYBE some y-sort shenanigans

**Comment by Jakllp** [comment]
Yea this is ysort and might not be easily fixable as I don't think there is any way to tell godot to calculate ysort differently and we need the chest to be positioned like that inside their own scene, same goes for the worm.  
Maybe not but yea

**Comment by Thyrexx** [comment]
Before 84c2980 the whole worm node was shiftet to the top to have the sprite and everything else at the right position. This meant that the origin of the node for y-sort was not the the bottom of the worm.  
In 84c2980 the worm node was resetet back to (0,0) but everything else up. So the look is the same but the origin for y-sort should be at the bottom.  
Not testet if it really is better
