### ISSUE TITLE
Spiders "attacking" through corners

### ISSUE THREAD

**Issue by Jakllp** [Three-s-A-Crowd-Games/Gerda#78]
This spider will play the attack animation (it does not deal damage):  
![image](https://github.com/Three-s-A-Crowd-Games/Gerda/assets/57708725/fb5f47b6-8cb6-4b01-8e73-b59896cef0f7)

**Comment by Jakllp** [comment]
Their attack is a bit weird in general

**Comment by Thyrexx** [comment]
Now it doesn't attack but deal damage. See #105
