### ISSUE TITLE
Mirrored item

### ISSUE THREAD

**Issue by Thyrexx** [Three-s-A-Crowd-Games/Gerda#90]
The sprite from an item is mirrored ~~sometimes~~ always.
![grafik](https://github.com/Three-s-A-Crowd-Games/Gerda/assets/96577754/3c07ae0d-bfc9-458c-bf42-6d90dbe5b23f)
![grafik](https://github.com/Three-s-A-Crowd-Games/Gerda/assets/96577754/847516b7-367d-4ca1-a9b6-152b15ff6e31)

**Comment by Jakllp** [comment]
Not really mirrored. Could be an hframe/vframe issue
